### ISSUE TITLE
Fix condition

### ISSUE THREAD

**Issue by funny-falcon** [flyingmutant/rand#5]
https://github.com/flyingmutant/rand/blob/c8c7e26aa2ff85d8922a16d9ec6c963b5be45f57/rand.go#L206
`n < pos` should be `pos > 0`

**Comment by flyingmutant** [comment]
Hm, why? Can you show an example where the code is incorrect?

**Comment by funny-falcon** [comment]
It depends on definition of "incorrect".
Current code doesn't generate error. But it takes only 4 bytes from 8 byte value.

**Comment by flyingmutant** [comment]
Can you please provide an example where `Read()` is not using all `pos` bytes available in `val`?

**Comment by funny-falcon** [comment]
ah, you're right: I missed pos was copied.
