### ISSUE TITLE
rand lib benchmarks

### ISSUE THREAD

**Issue by denisgolius** [flyingmutant/rand#6]
Hi there!

Do you have some benchmarks regarding https://github.com/valyala/fastrand ?

**Comment by flyingmutant** [comment]
Yep! See the "Compared to github.com/valyala/fastrand" [section](https://github.com/flyingmutant/rand/blob/dbb28395659ab826f75b3e56612df5c40515799c/README.md?plain=1#L118-L128) in the README.
