### ISSUE TITLE
Is it thread safe?

### ISSUE THREAD

**Issue by zedd3v** [flyingmutant/rand#7]

**Comment by flyingmutant** [comment]
Quoting [the documentation](https://pkg.go.dev/pgregory.net/rand#pkg-overview):

> Top-level functions that do not have a [Rand](https://pkg.go.dev/pgregory.net/rand#Rand) parameter, such as [Float64](https://pkg.go.dev/pgregory.net/rand#Float64) and [Int](https://pkg.go.dev/pgregory.net/rand#Int), use non-deterministic goroutine-local pseudo-random data sources that produce different sequences of values each time a program is run. These top-level functions are safe for concurrent use by multiple goroutines, and their performance does not degrade when the parallelism increases. [Rand](https://pkg.go.dev/pgregory.net/rand#Rand) methods and functions with [Rand](https://pkg.go.dev/pgregory.net/rand#Rand) parameter are not safe for concurrent use, but should generally be preferred because of determinism, higher speed and quality.
